default_language_version:
  python: python3
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort
        args: [
          "-c",
        ]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-quotes ]
  - repo: local
    hooks:
      - id: poetry
        name: poetry check
        entry: poetry check
        pass_filenames: false
        language: system
        files: ^pyproject\.toml$

